
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: "{{ .Chart.Name }}-gateway"
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name:  "{{ .Chart.Name }}-http"
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ .Chart.Name }}-http-route"
spec:
  parentRefs:
  - name: "{{ .Chart.Name }}-gateway"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: "{{ .Chart.Name }}-service"
      port: 80