---
apiVersion: v1
kind: Service
metadata:
  name: foodfinder-api
  namespace: foodfinder
  labels:
    app: foodfinder-api
spec:
  type: ClusterIP
  externalIPs: [192.168.22.1]
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: foodfinder-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodfinder-api
  namespace: foodfinder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foodfinder-api
  template:
    metadata:
      labels:
        app: foodfinder-api
    spec:
      containers:
      - name: foodfinder-api
        image: vnedkov/foodfinder-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ELASTICSEARCH_URL
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: ELASTICSEARCH_URL
        - name: ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: ELASTICSEARCH_USER
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: ELASTICSEARCH_PASSWORD
        - name: ELASTICSEARCH_INDEX
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: ELASTICSEARCH_INDEX
---
# L2 announcement policy for the service
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: foodfinder-api
  namespace: foodfinder
spec:
  externalIPs: true
  loadBalancerIPs: true
  interfaces:
    - eth0
  serviceSelector:
    matchLabels:
      app: foodfinder-api
{{- include "helm.selectorLabels" . | nindent 6 }}